"""empty message

Revision ID: 2e06bc5023f4
Revises: 
Create Date: 2020-05-27 22:47:58.856000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e06bc5023f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('priceperunit', sa.Float(), nullable=True),
    sa.Column('store', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pickup', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('tag',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_table('Item')
    # ### end Alembic commands ###
