"""empty message

Revision ID: 3e5e0c48fd9e
Revises: 9e65f2e835e2
Create Date: 2020-05-27 23:09:21.756000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e5e0c48fd9e'
down_revision = '9e65f2e835e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('tag')
    op.add_column('Item', sa.Column('priceperunit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Item', 'priceperunit')
    op.create_table('tag',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_table('name')
    # ### end Alembic commands ###
