"""empty message

Revision ID: 4bd6be10f8b0
Revises: 
Create Date: 2020-05-23 16:36:48.011000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bd6be10f8b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tag')
    op.drop_table('Store')
    op.drop_table('Item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('priceperunit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('store', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('Store',
    sa.Column('name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pickup', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('Tag',
    sa.Column('uuid', postgresql.ARRAY(postgresql.UUID()), autoincrement=False, nullable=True),
    sa.Column('name', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
